2025-05-28 01:37:10 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 01:38:51 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 01:39:33 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 01:42:09 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-lstm: ModelTrainer.train_model() missing 1 required positional argument: 'features_result'
2025-05-28 01:42:09 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_gru
2025-05-28 01:44:44 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-gru: ModelTrainer.train_model() missing 1 required positional argument: 'features_result'
2025-05-28 01:44:44 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_transformer
2025-05-28 01:47:21 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-transformer: ModelTrainer.train_model() missing 1 required positional argument: 'features_result'
2025-05-28 01:47:21 - deep_learning - INFO - [logger.py:103] - Starting training for ETH_4h_lstm
2025-05-28 01:52:26 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 01:55:01 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-lstm: ModelTrainer.train_model() missing 1 required positional argument: 'features_result'
2025-05-28 01:55:01 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_gru
2025-05-28 01:56:55 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 01:59:37 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-lstm: ModelTrainer.train_model() missing 1 required positional argument: 'features_result'
2025-05-28 01:59:37 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_gru
2025-05-28 02:01:55 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 02:04:40 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-lstm: "['target'] not found in axis"
2025-05-28 02:04:40 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_gru
2025-05-28 02:19:16 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_lstm
2025-05-28 02:19:16 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-lstm: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:16 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_gru
2025-05-28 02:19:16 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-gru: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:16 - deep_learning - INFO - [logger.py:103] - Starting training for BTC_4h_transformer
2025-05-28 02:19:17 - deep_learning - ERROR - [logger.py:111] - Error training BTC-4h-transformer: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:17 - deep_learning - INFO - [logger.py:103] - Starting training for ETH_4h_lstm
2025-05-28 02:19:17 - deep_learning - ERROR - [logger.py:111] - Error training ETH-4h-lstm: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:17 - deep_learning - INFO - [logger.py:103] - Starting training for ETH_4h_gru
2025-05-28 02:19:18 - deep_learning - ERROR - [logger.py:111] - Error training ETH-4h-gru: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:18 - deep_learning - INFO - [logger.py:103] - Starting training for ETH_4h_transformer
2025-05-28 02:19:18 - deep_learning - ERROR - [logger.py:111] - Error training ETH-4h-transformer: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:18 - deep_learning - INFO - [logger.py:103] - Starting training for SOL_4h_lstm
2025-05-28 02:19:18 - deep_learning - ERROR - [logger.py:111] - Error training SOL-4h-lstm: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:18 - deep_learning - INFO - [logger.py:103] - Starting training for SOL_4h_gru
2025-05-28 02:19:18 - deep_learning - ERROR - [logger.py:111] - Error training SOL-4h-gru: 'DataPreprocessor' object has no attribute 'prepare_features'
2025-05-28 02:19:18 - deep_learning - INFO - [logger.py:103] - Starting training for SOL_4h_transformer
2025-05-28 02:19:19 - deep_learning - ERROR - [logger.py:111] - Error training SOL-4h-transformer: 'DataPreprocessor' object has no attribute 'prepare_features'
